version: "2"
exclude_patterns:
  - "node_modules"
  - "src/api/"
  - "*.test.js"
  - "**.scss"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: true
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: false
  identical-code:
    enabled: false
