language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
    - "node_modules"
  paths:
    - cache/Cypress
script:
    - 'export CYPRESS_CACHE_FOLDER=../../cache/Cypress'
    - 'export CYPRESS_CACHE_FOLDER=cache/Cypress'
    - npm test
notifications:
  email: false  
